### PR TITLE
Adds support for multi nodes per virtual site

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)

### CODE REVIEW

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: This is the big PR that we tried to split up, but found that it would be better to just have a cohesive, though very large, change set. Let me know if you'd like to get a on a VC at some point to interactively review all the changes. Here are some highlights:

* The changes to the 15 virtual site files are to move the old  site-wide`network` field to a property of each machine at the site.
* `_default_virtual.jsonnet`: this is a new virtual site template, which is by and large the same as for physical sites, but moving the `network` field to a property of each machine.
* `site_virtual_lib[_test].jsonnet`: new site library for virtual sites. Very similar to the standard site library with a few modifications to functions to account for differences in virtual sites. Plus a unit test file for checking basic functionality.
* All relevant formats now iterate over `std.objectFields(site.machines)` instead of iterating over `std.range(1, std.length(site.machines))`. This allow us the flexibility of having any number machines at a site, using arbitrary machine names.
* `v2/sites/annotations.json.jsonnet`: This v2 format differs from its v1 counterpart by including a new `Machine` field. Currently, the uuid-annotator assumes that every machine at a site uses the same network configuration. This new v2 format will allow the uuid-annotator to recognize per-machine network configs (like we have for virtual sites). Indeed, the uuid-annotator annotates at the machine level, and creates this "Machine" field itself. This additional will simplify the uuid-annotator configuration and will allow per-machine network configs.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MyiOJKE7O_sp8baAJob:bj5u1b4)* status: 0 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[formats/v1/sites/annotations.json.jsonnet, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-1RF2abb3thkpx_o:-MymbVoc6cbnGGioDwjd:b15fvkv) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v1/sites/annotations.json.jsonnet#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How do we handle virtual?
</blockquote></details>

The uuid-annotator is presently not really compatible with virtual nodes, especially in the future case where we may have more than one node per virtual site. Virtual nodes don't have a `network` field at the site level, but instead at the machine level. We talked about making changes to the uuid-annotator to start consuming the v2 version instead, which has network information at the machine level as opposed to site level. This was just my way of expressing that the v1 format will only really be valid for physical nodes, and that in the very near future we migrate the uuid-annotator to start using the v2 format.

I could modify this format to include all servers, physical and virtual, and for virtual nodes those functions would just return an empty string?

 
___
*[formats/v2/sites/annotations.json.jsonnet, line 15 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-4ZX-v0ZFfKZxS9c:-MynWe_Y35Kt11aY19DZ:btudmko) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v2/sites/annotations.json.jsonnet#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The object returned by `Network()` seems like it belongs in this format rather than in the library. Is there a physical/virtual agnostic way to access the IPv4 and IPv6 fields for this file?
</blockquote></details>

I have abstracted it behind this `Network()` function of each library because the value returned comes from two different places, depending on whether the site is virtual or physical. For physical sites it comes from `site.network.ipv[46].prefix`, whereas for virtual sites it comes from `site.machines[mlab + N].network.ipv[46].address`. Unless I'm overlooking something (not unlikely), the only way to get rid of this function would be to move the physical/virtual logic from the libraries and into this format.
___
*[lib/site_virtual.jsonnet, line 25 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-MylzpG08N-b7ua3Bj40:-MynOE4X4FyJ-Jw8DYbo:b-o9y786) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/lib/site_virtual.jsonnet#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it true that Virtual sites do not have prefixes? Does the /32 or /128 not work in this context?

Do virtual site annotations need/could-use this also?
</blockquote></details>

I think I meant for this to represent a site-level prefix like we have at physical sites, but not on virtual sites, as opposed to machine-level prefixes, which are only present on virtual nodes.  Here, I could just return the machine-level "prefix" for formats that are really looking for a site-level prefix. However, that would only work or be valid at virtual sites with only a single node. I'm not sure it would translate at virtual sites with more than a single node. Granted, all we have currently are virtual sites with single nodes, but I was trying to think ahead to the time when we have multiple VMs at a virtual site.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[formats/v1/sites/annotations.json.jsonnet, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-1RF2abb3thkpx_o:-MyvndtgC28I5T8_eikG:bfp8p29) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v1/sites/annotations.json.jsonnet#L14)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The uuid-annotator is presently not really compatible with virtual nodes, especially in the future case where we may have more than one node per virtual site. Virtual nodes don't have a `network` field at the site level, but instead at the machine level. We talked about making changes to the uuid-annotator to start consuming the v2 version instead, which has network information at the machine level as opposed to site level. This was just my way of expressing that the v1 format will only really be valid for physical nodes, and that in the very near future we migrate the uuid-annotator to start using the v2 format.

I could modify this format to include all servers, physical and virtual, and for virtual nodes those functions would just return an empty string?

 
</blockquote></details>

I missed that this was the v1 format. Will only using physical sites remain compatible with the current cloud nodes?

This format uses the explicit "exploded" `Network` format I cite in later comments for the v2 annotation format. This format does not belong in the library.

If the virtual library supported NetworkPrefix, could the v2 annotation format also use this approach?

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I've made some changes that I believe address your concerns. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-Myxj16x1dIdxrTTSmPE:b-435m3k)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[formats/v1/sites/annotations.json.jsonnet, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-1RF2abb3thkpx_o:-Myx-zbb6P2g1VynuqDc:bhis95s) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v1/sites/annotations.json.jsonnet#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I missed that this was the v1 format. Will only using physical sites remain compatible with the current cloud nodes?

This format uses the explicit "exploded" `Network` format I cite in later comments for the v2 annotation format. This format does not belong in the library.

If the virtual library supported NetworkPrefix, could the v2 annotation format also use this approach?
</blockquote></details>

True, it would not remain compatible with existing virtual sites. I have reworked the `NetworkPrefix()` function to accept a `machine` parameter to work for virtual sites and physical sites. I have also removed the `Machine.Network()` function, which is now supplanted by the expanded `NetworkPrefix()` function.
___
*[formats/v2/sites/annotations.json.jsonnet, line 15 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-4ZX-v0ZFfKZxS9c:-Myx9BEt5thUUeJk3bD6:b2x65c2) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v2/sites/annotations.json.jsonnet#L15)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have abstracted it behind this `Network()` function of each library because the value returned comes from two different places, depending on whether the site is virtual or physical. For physical sites it comes from `site.network.ipv[46].prefix`, whereas for virtual sites it comes from `site.machines[mlab + N].network.ipv[46].address`. Unless I'm overlooking something (not unlikely), the only way to get rid of this function would be to move the physical/virtual logic from the libraries and into this format.
</blockquote></details>

I believe I have addressed your concern here by removing this function, and having expanded the `NetworkPrefix()` function.
___
*[lib/site_virtual.jsonnet, line 25 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-MylzpG08N-b7ua3Bj40:-Myx9MAQ3_avCvXZ86dh:b3ylit2) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/lib/site_virtual.jsonnet#L25)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I think I meant for this to represent a site-level prefix like we have at physical sites, but not on virtual sites, as opposed to machine-level prefixes, which are only present on virtual nodes.  Here, I could just return the machine-level "prefix" for formats that are really looking for a site-level prefix. However, that would only work or be valid at virtual sites with only a single node. I'm not sure it would translate at virtual sites with more than a single node. Granted, all we have currently are virtual sites with single nodes, but I was trying to think ahead to the time when we have multiple VMs at a virtual site.
</blockquote></details>

I believe I have addressed this with the most recent changes. This function now accepts a `machine` parameter and works similarly for both virtual and physical sites.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[formats/v1/sites/annotations.json.jsonnet, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-1RF2abb3thkpx_o:-Mz1gwmwDadcKZqH15TE:b-hex2fy) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v1/sites/annotations.json.jsonnet#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since there is only one machine per site currently for virtual nodes, could this still work with a Virtual section (perhaps) limited to mlab1 only until we migrate off of v1?

Or, what would happen to the current virtual nodes if they restarted after this was published? What is the order of operations we need to take to migrate the virtual nodes to the v2 format?
</blockquote></details>

The new staging virtual site iad08 (part of this PR) has a single mlab4 node, which somewhat complicated the logic here, making it impossible to assume that all current  virtual sites contain only a single mlab1 node.

I'm not sure I understand what you mean by "migrate virtual nodes to the v2 format"? The things that will need to be migrated to the v2 format are not the nodes, but any services that consume the annotations. format. I'm likely missing something obvious in your comment, sorry.
___
*[lib/site.jsonnet, line 61 at r3](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mz1UhOh1bwlbyTPjiZM:-Mz1gU1PCnQQTnweDlFc:bn3uott) ([raw file](https://github.com/m-lab/siteinfo/blob/12a65b8f5247fad9422c0ae9381caa9530c33418/lib/site.jsonnet#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to eliminate the default value? (here and in virtual library)

For the v1 format, simply passing in "mlab1" should be equivalent. This would simplify the docstring. If it is helpful to have clarifying context, please add that to the format file.
</blockquote></details>

I tried that, and the build failed, because of iad08, the staging virtual site, which is part of this PR, which has only an mlab4 node. I then also thought that hiding some of the ugliness in the library was perhaps better than sticking it in the format itself.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I have moved the logic for handling virtual sites in deprecated v1 formats from the site libs and into the formats themselves. The deprecated v1 formats should WAI for single-machine virtual sites, as we have today. This means that these v1 formats should support the entire platform today, giving us time to migrate any consumers of those formats away from the v1 format to the newer v2 formats that support virtual sites properly.

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzR6jIH8XuDKnjKM7Ro:b-6wqi2z)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[formats/v1/sites/annotations.json.jsonnet, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mym-1RF2abb3thkpx_o:-MzR6aaqA5nj6JmkTQxD:b2nha9w) ([raw file](https://github.com/m-lab/siteinfo/blob/fee4656b1070fb639c289d62d711dec5b729fa9e/formats/v1/sites/annotations.json.jsonnet#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think I meant that every virtual site has only one node currently. And, iiuc, the v1 annotations format has one record per site. So, these seem potentially compatible as we transition.

By "migrate virtual nodes to the v2 format" I meant what steps do we need to take to update the uuid-annotator to use the v2 format without disrupting the current production virtual nodes. I'm sorry - I was being imprecise by using "node" as a stand in for "any services on the node that consume the annotations format". Since this format uses "mlab1" by default, what is the migration path for the staging node?
</blockquote></details>

ACK
___
*[lib/site.jsonnet, line 61 at r3](https://reviewable.io/reviews/m-lab/siteinfo/225#-Mz1UhOh1bwlbyTPjiZM:-MzR6d5-1celgIBXbu55:b2nha9w) ([raw file](https://github.com/m-lab/siteinfo/blob/12a65b8f5247fad9422c0ae9381caa9530c33418/lib/site.jsonnet#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The explanatory text here looks like it will be temporary, or at least obsolete after the transition to the v2 format. I would recommend keeping the libraries as simple as possible. Helpful notes for context can be placed in the v1 format.
</blockquote></details>

ACK

**Review by nkinkade — COMMENTED** [review]
Additionally, I added a v2 version for the geo.json format, which returns records for each machine, much live we've done for the v2 annotations.json format.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzR9c6VEMqWr0TIJBVN:b7mj2bu)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by nkinkade — COMMENTED** [review]
Sorry to tack on an unrelated thing to this PR, but I also made a one character commit to [update the IPv6 address for mlab-lax0t](https://github.com/m-lab/k8s-support/issues/666).

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzS6Agx10tfn1FfpcUD:bdf91ai)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Thank you, @nkinkade for bearing with me. One more possible improvement. I think we're very close.

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzVbA0QCVIIQCqzTrJm:b8359bt)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[formats/v1/sites/geo.json.jsonnet, line 1 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVb0myAQMwh08dEdSv:-MzVb0myAQMwh08dEdSw:b-o03aya) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/formats/v1/sites/geo.json.jsonnet#L1)):*
> ```Jsonnet
> // NOTE: this format is not compatible with virtual sites, and anything
> ```

(I actually don't know who or what uses the geo.json format -- is this part of the maptiles in the stats-pipeline?)
___
*[lib/site.jsonnet, line 52 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzV_azBCuNYG77yaxtl:-MzV_azBCuNYG77yaxtm:b-ymxlbq) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site.jsonnet#L52)):*
> ```Jsonnet
>   },
>   // Returns the IPv4 or IPv6 prefix for the physical site. The machine
>   // parameter is unused and only exists to support older formats that
> ```

Is this comment true? it looks like the machine parameter is ignored.
___
*[lib/site_virtual.jsonnet, line 22 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVavWv-FAKqpgS-O5c:-MzVavWv-FAKqpgS-O5d:b7v8m4d) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L22)):*
> ```Jsonnet
>     i
>   ),
>   // Returns the network address for the specified machine and protocol.
> ```

Thank you! this is much simpler!
___
*[lib/site_virtual.jsonnet, line 40 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVaPLO7-Vb0iyzaLaX:-MzVaPLO7-Vb0iyzaLaY:b2wdzzt) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L40)):*
> ```Jsonnet
>     project: $.machines['mlab' + i].project,
>     v4: {
>       ip: std.split($.machines['mlab' + i].network.ipv4.address, '/')[0],
> ```

Are the configured values for virtual sites an "address" or  "prefix"? The current usage seems to blur the lines.

For physical sites it is explicitly a prefix. The virtual name implies it is explicitly an address, but we can't use it as an address here.

Is it possible for the `NetworkPrefix()` method to append the appropriate CIDR subnet to the `address` value and simplify these uses of the "address"?

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I have made one commit and have one question. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzVwI9_0eV5behfxeB5:bfs4hs9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[formats/v1/sites/geo.json.jsonnet, line 1 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVb0myAQMwh08dEdSv:-MzVv1F77-Ivy6iSJLvG:b-5a2eps) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/formats/v1/sites/geo.json.jsonnet#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

(I actually don't know who or what uses the geo.json format -- is this part of the maptiles in the stats-pipeline?)
</blockquote></details>

Roberto let me know in Slack (and the standup) that he believes the only thing using that format is: https://www.measurementlab.net/status/

I have modified the v2 version of that format to not include machine name, nor network info, and have restored the `name` field to reflect the site name.  Later, I can make modifications to the website code to just not expose IP network information for the site.
___
*[lib/site.jsonnet, line 52 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzV_azBCuNYG77yaxtl:-MzVgK99CV9cnkOCt1r-:b3cgi1j) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site.jsonnet#L52)):*
Yes, it is ignored, and I _believe_ that is what my comment is saying:

> The machine parameter is unused

Am I reading my own comment incorrectly, or maybe I have phrased it in a way that is not as easy to understand as it should be?
___
*[lib/site_virtual.jsonnet, line 40 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVaPLO7-Vb0iyzaLaX:-MzVhS7N9yvnbX3ld1oZ:b-oqtmv3) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are the configured values for virtual sites an "address" or  "prefix"? The current usage seems to blur the lines.

For physical sites it is explicitly a prefix. The virtual name implies it is explicitly an address, but we can't use it as an address here.

Is it possible for the `NetworkPrefix()` method to append the appropriate CIDR subnet to the `address` value and simplify these uses of the "address"?
</blockquote></details>

It sounds like your main concern here is terminology. `10.0.0.1/32` is a valid "address" specification, just written out using CIDR notation. On the other hand, I believe you are correct that a /32 or /128 CIDR-notated address is indeed _not_ really a "prefix", at least in the way anyone might usually think about it. Is it possible that it could be enough to just rename the function `NetworkPrefix()` to something like `NewtorkCIDR()`? This way we can maintain the CIDR notation we have always used for network configurations, keeping parity between physical and virtual sites, where physical sites have prefixes in CIDR notation and virtual machines have addresses in CIDR notation.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[lib/site.jsonnet, line 52 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzV_azBCuNYG77yaxtl:-MzVxjYH0GpOBzGJf3Jw:b2mv4ps) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site.jsonnet#L52)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Yes, it is ignored, and I _believe_ that is what my comment is saying:

> The machine parameter is unused

Am I reading my own comment incorrectly, or maybe I have phrased it in a way that is not as easy to understand as it should be?
</blockquote></details>

Sorry - I think I read "unused" as "used".
___
*[lib/site_virtual.jsonnet, line 40 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVaPLO7-Vb0iyzaLaX:-MzVyJsH5hcIBFcbKWZp:by7s0d) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L40)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It sounds like your main concern here is terminology. `10.0.0.1/32` is a valid "address" specification, just written out using CIDR notation. On the other hand, I believe you are correct that a /32 or /128 CIDR-notated address is indeed _not_ really a "prefix", at least in the way anyone might usually think about it. Is it possible that it could be enough to just rename the function `NetworkPrefix()` to something like `NewtorkCIDR()`? This way we can maintain the CIDR notation we have always used for network configurations, keeping parity between physical and virtual sites, where physical sites have prefixes in CIDR notation and virtual machines have addresses in CIDR notation.
</blockquote></details>

Hmm - okay - I wasn't thinking that something like `10.0.0.1/32` was properly an "address". But, I think you're more right than I was.

I like the suggestion of changing NetworkPrefix to NetworkCIDR.

All that said, my suggestion to to try to simplify the usage of the "address" field rather than having to `std.split` it every time. There are currently more usages with a split than in `NetworkPrefix`/CIDR. And, in this case we know it will always be a /32 or /128 right?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[lib/site_virtual.jsonnet, line 40 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVaPLO7-Vb0iyzaLaX:-MzW64ms01oInQ4N7P4p:b70f37m) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm - okay - I wasn't thinking that something like `10.0.0.1/32` was properly an "address". But, I think you're more right than I was.

I like the suggestion of changing NetworkPrefix to NetworkCIDR.

All that said, my suggestion to to try to simplify the usage of the "address" field rather than having to `std.split` it every time. There are currently more usages with a split than in `NetworkPrefix`/CIDR. And, in this case we know it will always be a /32 or /128 right?
</blockquote></details>

I have renamed the `NetworkPrefix()` function to `NetworkCIDR()`.

As far as the CIDR notation for virtual addresses always being /32 or /128, the only exception to this I can imagine might be for IPv6. I have now learned a deal more about how GCE implements IPv6. A dual stack VPC subnet gets assigned a /64. Each dual stack VM in that subnet gets assigned a /96 from the subnet's /64. When the VM boots, the [GCE Guest Agent](https://cloud.google.com/compute/docs/images/guest-environment) invokes `dhclient` to get an IPv6 address from the metadata server, which returns the first address in the /96 prefix, and this gets assigned the primary network interface. However, the VM can use any address in the /96. I could imagine a world in which we have more than just NDT running on virtual nodes. If this were the case, then the network "prefix" could possibly be /96, such that each experiment could get its own IPv6 address. 

As I wrote the above, I realized that perhaps `site.machines[N].network.v6.address` might no longer be the right field name for IPv6 in that future world. But I guess we could make modifications to the naming at that time, if it ever comes? What do you think?

**Review by stephen-soltesz — APPROVED** [review]
Thank you, @nkinkade :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/225#-:-MzWMrrJ0YmK7gQjTSox:b8bzajv)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[lib/site_virtual.jsonnet, line 40 at r5](https://reviewable.io/reviews/m-lab/siteinfo/225#-MzVaPLO7-Vb0iyzaLaX:-MzWMmpVBa4rHWseElUm:b-837i3v) ([raw file](https://github.com/m-lab/siteinfo/blob/4986ab8285f6691cf3756bb8465e1a1ee978459f/lib/site_virtual.jsonnet#L40)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have renamed the `NetworkPrefix()` function to `NetworkCIDR()`.

As far as the CIDR notation for virtual addresses always being /32 or /128, the only exception to this I can imagine might be for IPv6. I have now learned a deal more about how GCE implements IPv6. A dual stack VPC subnet gets assigned a /64. Each dual stack VM in that subnet gets assigned a /96 from the subnet's /64. When the VM boots, the [GCE Guest Agent](https://cloud.google.com/compute/docs/images/guest-environment) invokes `dhclient` to get an IPv6 address from the metadata server, which returns the first address in the /96 prefix, and this gets assigned the primary network interface. However, the VM can use any address in the /96. I could imagine a world in which we have more than just NDT running on virtual nodes. If this were the case, then the network "prefix" could possibly be /96, such that each experiment could get its own IPv6 address. 

As I wrote the above, I realized that perhaps `site.machines[N].network.v6.address` might no longer be the right field name for IPv6 in that future world. But I guess we could make modifications to the naming at that time, if it ever comes? What do you think?
</blockquote></details>

Okay.

**Pull request merged**
