### PR TITLE
Updates README with info useful to dev/API users

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Thank you for writing this up. A few comments to help clarify and simplify.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-Mok3-0c-O9EGn7MI-ny:bm3qb5j)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1HC_7qHQ8pL_jQqB:-Mok1HC_7qHQ8pL_jQqC:bdr3iwp) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L6)):*
> ```Markdown
> 
> This repository is responsible for recording, tracking and publishing public
> information about every M-Lab site, server and service. All of the raw
> ```

s/service/measurement service/
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok34jR6CRp9MMQ7-1N:-Mok1TvH1gaOCrUeaiYd:b-84umjs) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L12)):*
I recommend leaving off the last sentence and moving that to the later sections of the README. These are implementation details rather than how to use/interpret this information.

> ```
> Artifacts created by this repository are stored in a Google Cloud
> Storage bucket and made public through a GCP Loadbalancer backed by the
> bucket.
> ```
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1WnU6LuzhRaYQVmG:-Mok1WnU6LuzhRaYQVmH:b-f83v4s) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L16)):*
> ```Markdown
> bucket.
> 
> There are currently two API versions, v1 and v2. Indexes to the resources
> ```

Why do we still have two versions? I find this confusing. What would it take to get down to only v2?
___
*[README.md, line 23 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1gA4Br8MRbLQhpTi:-Mok1gA4Br8MRbLQhpTj:b-m7u61o) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L23)):*
> ```Markdown
> 
> The v2 API does not provide all of the same resources as v1, but instead the v1
> resources where there was a change from the v1 version. That is to say, not all
> ```

Please rephrase the first sentence (I'm not sure it reads correctly).
___
*[README.md, line 41 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok21jX1xd_0OO5ZYBQ:-Mok21jX1xd_0OO5ZYBR:b-2gmhwt) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L41)):*
> ```Markdown
> 
> **NOTE**: v1 hostnames are no longer supported on the M-Lab platform and will
> not resolve through DNS.
> ```

We should stop publishing these in that case. How many of the v1 formats can be retired entirely?
___
*[README.md, line 50 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok2Q2NAt4s4qlcGsjr:-Mok2Q2NAt4s4qlcGsjs:bp0uys5) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L50)):*
> ```Markdown
> * `./retired/annotations.json`: the same as annotations.json below, but for
>   sites which have been retired and are no longer in active service.
> * `./sites/annotations.json`: mostly for internal use, consumed by the
> ```

s/mostly for internal use, //

I wouldn't mention "internal use" any where else either. Listing specific users within the m-lab system would be welcome, but not necessary if the content description is clear enough.

**Review by phillipa — COMMENTED** [review]
"The v2 API does not provide all of the same resources as v1, but instead the v1
resources where there was a change from the v1 version. That is to say, not all
v1 resources are deprecated, except in the case where there is a v2 resources
with the same name, in which case the v2 resource should always be used.
Additionally, the v2 API contains a few resources which did not exist when the
v1 API was created, and are therefore specific to v2." <--- this is confusing. So they need to check V2 and if there is nothing check V1?

**Review by phillipa — COMMENTED** [review]
Is this a change between V1 and V2 of the platform or of /this/ API? If it's not directly relevant to using this API maybe this is too much detail?

**Review by nkinkade — COMMENTED** [review]
@phillipa: Do my replies to @stephen-soltesz below, and the corresponding changes I've made, address your questions/concerns?

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-MooA8WQ3RJc4FTsX8vD:bhfem56)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1HC_7qHQ8pL_jQqB:-Monyoga4DgvW2B1h_qW:b-a2ujfl) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/service/measurement service/
</blockquote></details>

Changed.
___
*[README.md, line 12 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok34jR6CRp9MMQ7-1N:-Monyx1q8cMHBCRrn1Z5:bhii2ez) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend leaving off the last sentence and moving that to the later sections of the README. These are implementation details rather than how to use/interpret this information.

> ```
> Artifacts created by this repository are stored in a Google Cloud
> Storage bucket and made public through a GCP Loadbalancer backed by the
> bucket.
> ```

</blockquote></details>

Removed. I didn't move it to a later section.
___
*[README.md, line 16 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1WnU6LuzhRaYQVmG:-Moo-3SP59PeGxp2jgf4:b-d8xug9) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why do we still have two versions? I find this confusing. What would it take to get down to only v2?
</blockquote></details>

For backward compatability, I imagine. That is, not breaking integrations that might still be using v1 URLs, which includes M-Lab services. I couldn't find the specific PR, but I have recollection of porting over some v1 resources to the v2 URLs, but with no change in the content, and you pushing back saying that we definitely didn't want to duplicate a resource between two URLs/versions. I could be wrong.

There is nothing stopping us from moving every resource to v2 URLs, and just removing v1 altogether. This would involve changes to siteinfo, and then finding every place in our own code that uses siteinfo, and changing it to use a v2 URL. As far as I know, we have no idea who else may be consuming the siteinfo "API" outside of M-Lab. Removing v1 URLs  could possibly break third-party usage.

Indeed, v1 resources that have been superseded by a v2 resource, are not just deprecated, but retired. At the very least we should probably stop publishing those particular v1 resources.
___
*[README.md, line 23 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1gA4Br8MRbLQhpTi:-Moo8vyC6rO8hiaoab69:bqofa8u) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please rephrase the first sentence (I'm not sure it reads correctly).
</blockquote></details>

I've rephrased by explicitly enumerating the v1 resources that are retired, and pointing people to use the v2 resource of the same name. And warning that those retired v1 resources, while still available right now, will be removed in the future.
___
*[README.md, line 41 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok21jX1xd_0OO5ZYBQ:-Moo9Btw633Q1Se2JtX1:bhqfr8i) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We should stop publishing these in that case. How many of the v1 formats can be retired entirely?
</blockquote></details>

The v1 format that can be removed immediately are:

* hostnames.json
* sites.json

I've already made changes to the documentation to note this, warning of their removal. This is a stopgap until we, possibly, retire v1 altogether and move everything to v2.
___
*[README.md, line 50 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok2Q2NAt4s4qlcGsjr:-MooA1bq5enClxDEa7zN:b-bywzhe) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/mostly for internal use, //

I wouldn't mention "internal use" any where else either. Listing specific users within the m-lab system would be welcome, but not necessary if the content description is clear enough.
</blockquote></details>

I've removed most instances of "internal use", except for things like the placeholders and zone diffs.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[README.md, line 16 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1WnU6LuzhRaYQVmG:-MpgZCCPBB0dXZinJyaV:b-bj2fco) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L16)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

For backward compatability, I imagine. That is, not breaking integrations that might still be using v1 URLs, which includes M-Lab services. I couldn't find the specific PR, but I have recollection of porting over some v1 resources to the v2 URLs, but with no change in the content, and you pushing back saying that we definitely didn't want to duplicate a resource between two URLs/versions. I could be wrong.

There is nothing stopping us from moving every resource to v2 URLs, and just removing v1 altogether. This would involve changes to siteinfo, and then finding every place in our own code that uses siteinfo, and changing it to use a v2 URL. As far as I know, we have no idea who else may be consuming the siteinfo "API" outside of M-Lab. Removing v1 URLs  could possibly break third-party usage.

Indeed, v1 resources that have been superseded by a v2 resource, are not just deprecated, but retired. At the very least we should probably stop publishing those particular v1 resources.
</blockquote></details>

Our goal is to make interpreting this service and using it as simple as possible. I would advocate for moving our own usage to a single version (v2).

Here, we don't need to describe the v1 version b/c any existing user is already using it. Adding a note "earlier versions are deprecated and in process of being decommissioned" would make it clear that there had been earlier versions but they're no longer supported.

For future, it is possible to log GCS requests to see whether certain paths are being used at all. I would not prioritize that ahead of making all the v2 resources available and labeling the v1 resources as deprecated.
___
*[README.md, line 23 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok1gA4Br8MRbLQhpTi:-Mpgf32x34WeWW4WsA04:bn6bewc) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L23)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I've rephrased by explicitly enumerating the v1 resources that are retired, and pointing people to use the v2 resource of the same name. And warning that those retired v1 resources, while still available right now, will be removed in the future.
</blockquote></details>

I'm growing inclined to not even mention v1 now.
___
*[README.md, line 41 at r1](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mok21jX1xd_0OO5ZYBQ:-Mpgf9e6CeZRCmpQq-Nn:bqutey0) ([raw file](https://github.com/m-lab/siteinfo/blob/37abd723d8d5db5f3dbaf410b023b5a3dc2472cb/README.md#L41)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The v1 format that can be removed immediately are:

* hostnames.json
* sites.json

I've already made changes to the documentation to note this, warning of their removal. This is a stopgap until we, possibly, retire v1 altogether and move everything to v2.
</blockquote></details>

Please let's work toward retiring v1 altogether.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I'm replying in the general conversation thread here because, I'm wondering if we need to step back and find a way to make this PR work so that we have _some_ documentation instead of none. We may want to retire the v1 altogether, but meanwhile I imagine we want at least some documentation where previously we had none. Is the current state of the PR good enough for now, since migrating away from v1 seems like separate issue.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-Mpgv2PY6BfuKuGyU-xH:bkindhw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Okay, I've suggested at least reordering the information to emphasize the v2 data / links over the v1 information.

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-Mph0NQaAcR6WEqNngvV:b-pp2k6r)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[README.md, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mph-f2oCLHR3LLQzGHC:-Mph-f2p5YZgxvM4n9Z7:bw707ux) ([raw file](https://github.com/m-lab/siteinfo/blob/cbe2a02a06dda80dced130591c3b3421141c604c/README.md#L14)):*
> ```Markdown
> interface.
> 
> There are currently two API versions, v1 and v2. Indexes to the resources
> ```

Please lead with v2. Make it easier to find and use the v2 links than the v1 links. Right now they're placed equally or with an implicit bias towards v1 (b/c it's listed first).
___
*[README.md, line 19 at r2](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mph0DOJ8HKxp32aL871:-Mph0DOK4Rx7oL6NDBYz:b-87d26d) ([raw file](https://github.com/m-lab/siteinfo/blob/cbe2a02a06dda80dced130591c3b3421141c604c/README.md#L19)):*
> ```Markdown
> * <https://siteinfo.mlab-oti.measurementlab.net/v1/index.html>
> * <https://siteinfo.mlab-oti.measurementlab.net/v2/index.html>
> ```

I would place all the v2 section below here. I would move the v1 link above below.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-MphY38x8WV_eTNVfo47:b-e77fnf)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[README.md, line 14 at r2](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mph-f2oCLHR3LLQzGHC:-MphY1nH8kJYcO7PTohp:b-896fix) ([raw file](https://github.com/m-lab/siteinfo/blob/cbe2a02a06dda80dced130591c3b3421141c604c/README.md#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please lead with v2. Make it easier to find and use the v2 links than the v1 links. Right now they're placed equally or with an implicit bias towards v1 (b/c it's listed first).
</blockquote></details>

Done.
___
*[README.md, line 19 at r2](https://reviewable.io/reviews/m-lab/siteinfo/213#-Mph0DOJ8HKxp32aL871:-MphY2JZ79BGcjNT0eVE:b-896fix) ([raw file](https://github.com/m-lab/siteinfo/blob/cbe2a02a06dda80dced130591c3b3421141c604c/README.md#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I would place all the v2 section below here. I would move the v1 link above below.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
Perfect, thank you. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/siteinfo/213#-:-MphYN8H5NqukWnM6lPH:b-elx1ud)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by phillipa** [comment]
LGTM. thanks for updating.

**Pull request merged**
